version: '3'
services:
    nginx:
        image: "${DOCKER_USER}/lnmp-nginx:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - php
    php:
        image: "${DOCKER_USER}/lnmp-php:v1.2"
        build:
          context: .
          dockerfile: Dockerfile.php
        restart: always
        networks:
            - frontend
            - backend
        environment:
            - MYSQL_PASSWORD=root
        depends_on:
            - mysql
          
        networks:
            - backend
            - frontend   



    phpmyadmin:
          container_name: phpmyadmin
          image: daocloud.io/daocloud/phpmyadmin
          expose:
              - '80'
          ports:
              - "8080:80"
          environment:
              - PMA_ARBITRARY=0
              - PMA_HOST=mysql
              - PMA_MYSQL_ROOT_PASSWORD=root  
            #  - PMA_USER=root
            # - PMA_PASSWORD= Passw0rd
          depends_on:
              - mysql
          networks:
              - backend



    mysql:
        image: mysql:5.6
        volumes:
            - ./sql:/var/lib/mysql
        expose:
            - "33060"
        ports:
            - "3306:3306"
        environment:
            TZ: 'Asia/Taipei'
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: AirAlliance
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
volumes:
    sql:
networks:
    frontend:
    backend:
